/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'dateCreated' : Time,
  'name' : IDL.Text,
  'previousCredit' : IDL.Float64,
  'phoneNumber' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'previousCredit' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'ratePerUnit' : IDL.Float64,
  'customerId' : IDL.Nat,
  'netCredit' : IDL.Float64,
  'lemonQuantity' : IDL.Float64,
  'todayDebited' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreditPaymentTransaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionDate' : Time,
  'transactionType' : IDL.Text,
  'resultingCreditBalance' : IDL.Float64,
  'customerId' : IDL.Nat,
  'paymentAmount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const LemonSummary = IDL.Record({
  'totalCreditDue' : IDL.Float64,
  'totalRupeesCollected' : IDL.Float64,
  'totalProfitOrLoss' : IDL.Float64,
  'totalLemonsSold' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [Customer], []),
  'addTransaction' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
      [Transaction],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCreditPayment' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllCreditPaymentTransactions' : IDL.Func(
      [IDL.Record({})],
      [IDL.Vec(CreditPaymentTransaction)],
      ['query'],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreditPaymentTransactionsForCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CreditPaymentTransaction)],
      ['query'],
    ),
  'getCustomerBalance' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getCustomerById' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getLemonSummary' : IDL.Func([], [LemonSummary], ['query']),
  'getTransactionsForCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'payCreditDue' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'dateCreated' : Time,
    'name' : IDL.Text,
    'previousCredit' : IDL.Float64,
    'phoneNumber' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'previousCredit' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'ratePerUnit' : IDL.Float64,
    'customerId' : IDL.Nat,
    'netCredit' : IDL.Float64,
    'lemonQuantity' : IDL.Float64,
    'todayDebited' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreditPaymentTransaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionDate' : Time,
    'transactionType' : IDL.Text,
    'resultingCreditBalance' : IDL.Float64,
    'customerId' : IDL.Nat,
    'paymentAmount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const LemonSummary = IDL.Record({
    'totalCreditDue' : IDL.Float64,
    'totalRupeesCollected' : IDL.Float64,
    'totalProfitOrLoss' : IDL.Float64,
    'totalLemonsSold' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [Customer], []),
    'addTransaction' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
        [Transaction],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCreditPayment' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllCreditPaymentTransactions' : IDL.Func(
        [IDL.Record({})],
        [IDL.Vec(CreditPaymentTransaction)],
        ['query'],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreditPaymentTransactionsForCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CreditPaymentTransaction)],
        ['query'],
      ),
    'getCustomerBalance' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getCustomerById' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getLemonSummary' : IDL.Func([], [LemonSummary], ['query']),
    'getTransactionsForCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'payCreditDue' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };