/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreditPaymentTransaction {
  'id' : bigint,
  'transactionDate' : Time,
  'transactionType' : string,
  'resultingCreditBalance' : number,
  'customerId' : bigint,
  'paymentAmount' : number,
}
export interface Customer {
  'id' : bigint,
  'dateCreated' : Time,
  'name' : string,
  'previousCredit' : number,
  'phoneNumber' : string,
}
export interface LemonSummary {
  'totalCreditDue' : number,
  'totalRupeesCollected' : number,
  'totalProfitOrLoss' : number,
  'totalLemonsSold' : number,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'date' : Time,
  'previousCredit' : number,
  'totalAmount' : number,
  'ratePerUnit' : number,
  'customerId' : bigint,
  'netCredit' : number,
  'lemonQuantity' : number,
  'todayDebited' : number,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string, number], Customer>,
  'addTransaction' : ActorMethod<[bigint, number, number, number], Transaction>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCreditPayment' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllCreditPaymentTransactions' : ActorMethod<
    [{}],
    Array<CreditPaymentTransaction>
  >,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreditPaymentTransactionsForCustomer' : ActorMethod<
    [bigint],
    Array<CreditPaymentTransaction>
  >,
  'getCustomerBalance' : ActorMethod<[bigint], number>,
  'getCustomerById' : ActorMethod<[bigint], Customer>,
  'getLemonSummary' : ActorMethod<[], LemonSummary>,
  'getTransactionsForCustomer' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'payCreditDue' : ActorMethod<[bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];