/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'dateCreated' : Time,
  'name' : string,
  'phoneNumber' : string,
}
export interface LemonSummary {
  'totalCreditDue' : bigint,
  'totalRupeesCollected' : bigint,
  'totalProfitOrLoss' : bigint,
  'totalLemonsSold' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'date' : Time,
  'previousCredit' : bigint,
  'totalAmount' : bigint,
  'ratePerUnit' : bigint,
  'customerId' : bigint,
  'netCredit' : bigint,
  'lemonQuantity' : bigint,
  'todayDebited' : bigint,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<[string, string], Customer>,
  'addTransaction' : ActorMethod<[bigint, bigint, bigint, bigint], Transaction>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getCustomerBalance' : ActorMethod<[bigint], bigint>,
  'getCustomerById' : ActorMethod<[bigint], Customer>,
  'getLemonSummary' : ActorMethod<[], LemonSummary>,
  'getTransactionsForCustomer' : ActorMethod<[bigint], Array<Transaction>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];