/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'dateCreated' : Time,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'previousCredit' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'ratePerUnit' : IDL.Nat,
  'customerId' : IDL.Nat,
  'netCredit' : IDL.Nat,
  'lemonQuantity' : IDL.Nat,
  'todayDebited' : IDL.Nat,
});
export const LemonSummary = IDL.Record({
  'totalCreditDue' : IDL.Nat,
  'totalRupeesCollected' : IDL.Nat,
  'totalProfitOrLoss' : IDL.Nat,
  'totalLemonsSold' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], []),
  'addTransaction' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [Transaction],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getCustomerBalance' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getCustomerById' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getLemonSummary' : IDL.Func([], [LemonSummary], ['query']),
  'getTransactionsForCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'dateCreated' : Time,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'previousCredit' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'ratePerUnit' : IDL.Nat,
    'customerId' : IDL.Nat,
    'netCredit' : IDL.Nat,
    'lemonQuantity' : IDL.Nat,
    'todayDebited' : IDL.Nat,
  });
  const LemonSummary = IDL.Record({
    'totalCreditDue' : IDL.Nat,
    'totalRupeesCollected' : IDL.Nat,
    'totalProfitOrLoss' : IDL.Nat,
    'totalLemonsSold' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [Customer], []),
    'addTransaction' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [Transaction],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getCustomerBalance' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getCustomerById' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getLemonSummary' : IDL.Func([], [LemonSummary], ['query']),
    'getTransactionsForCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };